### ISSUE TITLE
Remove models after running tests

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/hoomd-tf#131]
We need to add clean-up code to all our tests so that we don't have a bunch of model folders left over each time the tests are run. This has been creating permission errors when people run tests on bluehive nodes.

**Comment by ziyueyang37** [comment]
Can I write a Makefile and do the test by 'make test' ?

**Comment by whitead** [comment]
Addressed by #148

**Comment by hgandhi2411** [comment]
@ziyueyang37 With your latest change, you forgot to `import shutil` in `test_utils.py` and `test_mpi_tensorflow.py`. 
Also, the `test_load_variables()` test fails due to this line `model_dir=self.tmp` because `self.tmp` is not defined.

**Comment by whitead** [comment]
Thank you @hgandhi2411. @ziyueyang37 these are probably from my modification of your PR. Please take a look at them.
